name: Broken Link Checker

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --accept 200,403,429 https://www.genzfrontir.com/sitemap.xml
          fail: true
          failIfEmpty: false # Allow empty if no links are found, to prevent workflow failure if sitemap is temporarily empty
          format: markdown
          jobSummary: true
          output: lychee/out.md
          checkbox: true
          token: ${{ secrets.GITHUB_TOKEN }}